# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        App\Entity\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: App\Entity\User\User
                property: username

    firewalls:
        main:
            provider: db_provider
            pattern: ^/
            anonymous: true
            form_login:
                default_target_path: app_index
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # where to redirect after logout
                # target: app_any_route

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        spadecrm:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout_on_user_change: true
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/guests, role: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
        - { path: ^/user, role: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
#        - { path: ^/$, role: [IS_AUTHENTICATED_FULLY] }
#        - { path: ^/guests, role: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
#        - { path: ^/crm-forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/permissionmatrix, roles: ROLE_SUPER_ADMIN }
#        - { path: ^/crm, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/hr, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/privacy-policy, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/, role: ROLE_USER }