<?php

namespace App\Repository\Guest;

use Doctrine\ORM\EntityRepository;

/**
 * GuestDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestDetailRepository extends EntityRepository
{
    /**
     * @param int $userId
     * @return int|mixed|string
     */
    public function getGuestData($userId)
    {
        $qb = $this->createQueryBuilder('g');
        $qb->select('g')
            ->where('g.user = :userId')
            ->setParameter('userId', $userId);

        return $qb->getQuery()->getResult();
    }
}
