<?php

namespace App\Repository\Master;

use App\Entity\Master\Resource;
use App\Entity\Master\ResourcePermission;

/**
 * ResourcePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcePermissionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $resources
     * @return array
     */
    public function constructArray($resources)
    {
        $resultArr = [];

        foreach ($resources as $resource) {
            /** @var Resource $resource */
            $resourcePermissions = $resource->getResourcePermissions();
            foreach ($resourcePermissions as $res) {
                /** @var ResourcePermission $res */
                $resourceName = $res->getResource()->getName();
                $permissionType = $res->getPermissionType()->getName();
                $resourceId = $res->getResource()->getId();
                $resultArr[$resourceName][$resourceId][$permissionType] = $permissionType;
            }
        }
        return $resultArr;
    }
}
