<?php

namespace App\Repository\User;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
//    public function getColleaguesInDepartment(User $user)
//    {
//        $qb = $this->createQueryBuilder('u');
//        $qb->select('u.username')->join('u.departmentId', 'd')
//            ->where('d.id = :departmentId')
//            ->andWhere('u.username != :currentUser')
//            ->setParameter('departmentId', $user->getDepartmentId())
//            ->setParameter('currentUser',$user->getUsername())
//        ;
//
//        return $qb->getQuery()->getResult();
//    }
}
